# pip install numpy

In [1]:
import numpy as np

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [4]:
np.array([10, 20, 30])

array([10, 20, 30])

In [5]:
arr = np.array([10, 20, 30])
arr, type(arr)

(array([10, 20, 30]), numpy.ndarray)

In [6]:
arr = np.array([10, 20, 30, 31.412515])
arr, type(arr)

(array([10.      , 20.      , 30.      , 31.412515]), numpy.ndarray)

In [7]:
arr = np.array([10, 20, 30, 31.412515, "hello"])
arr, type(arr)

(array(['10', '20', '30', '31.412515', 'hello'], dtype='<U32'), numpy.ndarray)

In [8]:
arr = np.array([10, 20, 30, 31.412515, True])
arr, type(arr)

(array([10.      , 20.      , 30.      , 31.412515,  1.      ]), numpy.ndarray)

In [9]:
arr = np.array([10, 20, 30, [31.412515, "hello"], ])
arr, type(arr)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [10]:
arr = np.array([ [10, 20, 30], [31.412515, "hello", 3], ])
arr, type(arr)

(array([['10', '20', '30'],
        ['31.412515', 'hello', '3']], dtype='<U32'),
 numpy.ndarray)

In [12]:
arr.size, len(arr)

(6, 2)

In [13]:
arr.shape

(2, 3)

# Fast mathematical Operations over array

In [15]:
arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

In [16]:
arr + 3

array([13, 23, 33, 43, 53])

In [17]:
lista = [10, 20, 30, 40, 50]
lista + 3

TypeError: can only concatenate list (not "int") to list

In [18]:
arr = np.array([10, 20, 30, 40, 50])
arr * 2

array([ 20,  40,  60,  80, 100])

In [19]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([101, 202, 303, 404, 505])

arr1 + arr2

array([111, 222, 333, 444, 555])

In [20]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([101, 202, 303, 404, 505])

arr1 + arr2

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

# Array din range

In [21]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(10, dtype=np.float64)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [25]:
arr = np.arange(100, 110)
arr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [27]:
arr.sum(), sum(arr)

(np.int64(1045), np.int64(1045))

In [28]:
arr.size, len(arr)

(10, 10)

In [30]:
arr.mean(), sum(arr)/ len(arr)

(np.float64(104.5), np.float64(104.5))

In [31]:
arr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [32]:
2 * arr + 1

array([201, 203, 205, 207, 209, 211, 213, 215, 217, 219])

In [33]:
arr > 105

array([False, False, False, False, False, False,  True,  True,  True,
        True])

# Operatii logice

In [34]:
arr[arr > 105]

array([106, 107, 108, 109])

In [35]:
conditie = arr > 105
arr[conditie]

array([106, 107, 108, 109])

In [36]:
arr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [37]:
arr[ arr % 2 == 0  ]

array([100, 102, 104, 106, 108])

In [39]:
arr[ (arr % 2 == 0)  & (arr > 105)]

array([106, 108])

In [40]:
arr[ (arr % 2 != 0)  | (arr < 105)]

array([100, 101, 102, 103, 104, 105, 107, 109])