In [97]:
import numpy as np
import matplotlib.pyplot as plt

In [98]:
BLUE = 	np.array([0, 43, 127, 255])
YELLOW = np.array([252, 209, 22, 255])
RED = np.array([206, 17, 38, 255])

In [99]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [100]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [101]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [102]:
WIDTH = 150
HEIGHT = 100
#                        4 - RGBA
SHAPE_IMAGINE = (HEIGHT, WIDTH,  4)

imagine_alba = np.ones(SHAPE_IMAGINE, dtype=np.uint8) * 255
imagine_alba


array([[[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        ...,
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]],

       [[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        ...,
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]],

       [[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        ...,
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]],

       ...,

       [[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        ...,
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]],

       [[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        ...,
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]],

       [[255

In [103]:
from PIL import Image

In [104]:
edited_image = Image.fromarray(imagine_alba)
edited_image.save("imagine_alba_10_x_10.png")

In [105]:
imagine_alba[0][0] = BLUE

In [106]:
imagine_alba[0, 0] = BLUE

In [107]:
imagine_alba[ : , : WIDTH // 3] = BLUE

In [108]:
imagine_alba[ : , WIDTH // 3 : 2 * WIDTH // 3 ] = YELLOW

In [109]:
imagine_alba[ : , 2 * WIDTH // 3 :  ] = RED

In [110]:
edited_image.save("steag_romania.png")