In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
type(arr), arr.dtype

(numpy.ndarray, dtype('int64'))

In [5]:
for i in range(20):
    print("in baza 10 = ", i,  " in binar = ", bin(i)[2:])

in baza 10 =  0  in binar =  0
in baza 10 =  1  in binar =  1
in baza 10 =  2  in binar =  10
in baza 10 =  3  in binar =  11
in baza 10 =  4  in binar =  100
in baza 10 =  5  in binar =  101
in baza 10 =  6  in binar =  110
in baza 10 =  7  in binar =  111
in baza 10 =  8  in binar =  1000
in baza 10 =  9  in binar =  1001
in baza 10 =  10  in binar =  1010
in baza 10 =  11  in binar =  1011
in baza 10 =  12  in binar =  1100
in baza 10 =  13  in binar =  1101
in baza 10 =  14  in binar =  1110
in baza 10 =  15  in binar =  1111
in baza 10 =  16  in binar =  10000
in baza 10 =  17  in binar =  10001
in baza 10 =  18  in binar =  10010
in baza 10 =  19  in binar =  10011


# 8 bits = 1 byte (octet)

In [7]:
2 ** 8 - 1

255

In [9]:
bin(2 ** 8 - 1)

'0b11111111'

In [10]:
bin(2 ** 8 )

'0b100000000'

In [12]:
arr = np.array([255, 256])
arr, arr.dtype

(array([255, 256]), dtype('int64'))

# UINT8 este de la 0 .. 255

In [15]:
arr = np.array([255, 253], dtype=np.uint8)
arr, arr.dtype

(array([255, 253], dtype=uint8), dtype('uint8'))

In [16]:
arr = np.array([255, 256], dtype=np.uint8)
arr, arr.dtype

OverflowError: Python integer 256 out of bounds for uint8

# INT8 este de la -128..127

In [18]:
arr = np.array([-128, 127], dtype=np.int8)
arr, arr.dtype

(array([-128,  127], dtype=int8), dtype('int8'))

In [19]:
arr = np.array([-128, 128], dtype=np.int8)
arr, arr.dtype

OverflowError: Python integer 128 out of bounds for int8

In [20]:
arr = np.array([-129, 127], dtype=np.int8)
arr, arr.dtype

OverflowError: Python integer -129 out of bounds for int8