In [25]:
import numpy as np
import matplotlib.pyplot as plt

In [26]:
BLACK = 	np.array([0, 0, 0, 255])
YELLOW = np.array([252, 209, 22, 255])
RED = np.array([206, 17, 38, 255])

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [30]:
WIDTH = 100
HEIGHT = 150
#                        4 - RGBA
SHAPE_IMAGINE = (HEIGHT, WIDTH,  4)

imagine_alba = np.ones(SHAPE_IMAGINE, dtype=np.uint8) * 255
imagine_alba


array([[[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        ...,
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]],

       [[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        ...,
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]],

       [[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        ...,
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]],

       ...,

       [[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        ...,
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]],

       [[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        ...,
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]],

       [[255

In [31]:
from PIL import Image

In [32]:
edited_image = Image.fromarray(imagine_alba)
edited_image.save("imagine_alba_10_x_10.png")

In [33]:
imagine_alba[ : , : WIDTH // 3] = BLACK

In [34]:
imagine_alba[ : , WIDTH // 3 : 2 * WIDTH // 3 ] = YELLOW

In [35]:
imagine_alba[ : , 2 * WIDTH // 3 :  ] = RED

In [36]:
edited_image.save("steag_germania.png")

In [37]:
arr = np.arange(10).reshape(2, 5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [38]:
arr.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [43]:
imagine_alba.shape

(150, 100, 4)

In [42]:
imagine_alba.T.shape

(4, 100, 150)

In [45]:
np.rot90(imagine_alba).shape

(100, 150, 4)

In [46]:
edited_T = Image.fromarray(np.rot90(imagine_alba))
edited_T.save("steag_germania_transpus.png")

In [47]:
edited_T = Image.fromarray(np.rot90(imagine_alba, 3))
edited_T.save("steag_germania_rotita.png")